files["reflection.txt"] = {
    run: () => {
        return new Promise(async resolve => {
            await runConsecutively([

                () => addLine("ENG2003 is a course that allowed me to transform my skills as a communicator, to both likeminded, and different audiences. I was provided a valuable platform to enhance my communication and my understanding of effective engineering practices. Throughout the course I had the opportunity to craft a unique and compelling cover letter, and the ability to choose my own topic for a technical report. Writing about the X-Minute city has allowed me to explore the intricacies of city planning, as well as truly understanding the depth of various adjacent topics such as the 15-Minute City and similar planning concepts. Writing the technical report was challenging yet enjoyable, as I was empowered through sharing what I had learned with the audience. Writing a technical report is a skill that I will hold on to and do my best to improve over time, as it is a skill that I foresee I will need in my future career. I have already put it to use in Arbalest Rocketry, where we write technical reports regarding the specifications of our rockets. I am particularly satisfied with having learned about letters of transmittals, as well as an editing history, as they have proven useful already within the Arbalest Rocketry context."),
                () => addLine("This course was not at all what I expected it to be, although I am not upset at that. I didn\’t think that technical reports were going to be such a focus, nor was resume and cover letter writing. I\’m glad to have gone over all of these skills, as prior to ENG2003 they lacked the finesse required for professional contexts. I had no experience writing professional technical reports, and learning about the IEEE style and the general layout of technical reports really refined my skills. I am a lot more confident in my abilities to communicate effectively in the workplace. I believe I still need to work on my presentation skills as well as my analysis and reflective skills, although ENG2003 has introduced me to ways to work on that. This includes the Gibb\’s Reflective cycle, which I have been using already to enhance my critical thinking and self-awareness skills."),
                () => addLine("ENG2003 has taught me a lot about how to approach different problems within the engineering world. Whether communicating important information to coworkers and colleagues, documenting important information for someone who may work on the project years down the road, or communicating to a potential employer as to why I am a good candidate for a position, I now will be able to apply the necessary skills to do so."),
                () => addLine("The concept of the 7 C\’s and the Axioms of Communication are also very important to me. They have allowed me to trim my communication to a digestible amount, enough for both industry professionals and bystanders to understand the topic at hand. They are concepts that, prior to ENG2003, I had not considered when communicating, especially with professors or fellow students. When writing emails, I constantly consider important factors such as being concise, concrete, clear, and courteous."),
            ]);
            resolve(true);
        });
    },
};