var startup = [
  () => addLine("Starting up " + info.hostname),
  () => threeDots(),
  () => addLine("Initializing kernel"),
  () => threeDots(),
  () => addLine("Mounting root file system"),
  () => threeDots(),
  () => addLine("Setting up network interfaces"),
  () => threeDots(),
  () => addLine("Starting system services"),
  () => threeDots(),
  () => showOK(),
  () => addLine("Configuring peripherals"),
  () => threeDots(),
  () => showOK(),
  () => addLine("Loading device drivers"),
  () => threeDots(),
  () => showOK(),
  () => addLine("Starting daemons"),
  () => threeDots(),
  () => showOK(),
  () => addLine("Finished booting up!"),
  () => addLine("┏──────────────────────────────────┓", 50, true),
  () => addLine("┃  Welcome to Tricia's Portfolio!  ┃", 50, true),
  () => addLine("┗──────────────────────────────────┛", 50, true),
  () => addLine("Type 'help' for a list of commands"),
  () => (proxyCanType.canType = true),
];